version: '3.8'

services:
  nats:
    image: nats:alpine
    command: '-js -m 8222'
    ports:
      - '4222:4222'
      - '8222:8222'
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:8222/varz']
      interval: 2s
      timeout: 2s
      retries: 15

  s3:
    image: adobe/s3mock:latest
    ports:
      - '9090:9090'
    environment:
      - initialBuckets=platform-documents
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:9090/']
      interval: 2s
      timeout: 2s
      retries: 10
