FROM golang:1.25-alpine AS builder
ARG SERVICE_NAME
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o app ./cmd/microservices/${SERVICE_NAME}/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/app .
COPY --from=builder /app/config ./config
CMD ["./app"]
