package events

// IngestPayload is generated by the Gateway when new data is ingested into the system.
// It supports a hybrid multimodal approach: short text via NATS, heavy files via BlobStore.
type IngestPayload struct {
	DocumentID  string            `json:"document_id"`            // Unique identifier of the document
	ContextText string            `json:"context_text,omitempty"` // Short text (e.g., descriptions, tags, micro-text)
	BlobURI     string            `json:"blob_uri,omitempty"`     // Claim Check URI for heavy files (PDF, images, etc.)
	MimeType    string            `json:"mime_type,omitempty"`    // e.g., "application/pdf" or "image/jpeg"
	SizeBytes   int64             `json:"size_bytes,omitempty"`   // File size in bytes
	Metadata    map[string]string `json:"metadata,omitempty"`     // Custom key-value pairs
}

// SearchPayload is generated by the Gateway when a user performs a search.
// It supports multimodal queries (e.g., searching by text, image, or both).
type SearchPayload struct {
	QueryText string `json:"query_text,omitempty"` // Search query text (fast delivery via NATS)
	BlobURI   string `json:"blob_uri,omitempty"`   // Image URI for visual search
	TopK      int    `json:"top_k"`                // Number of expected results
	MimeType  string `json:"mime_type"`
}

// Chunk represents a fragment of a document and its corresponding vector.
// Heavy documents are split into multiple chunks to fit LLM/Embedding context windows.
type Chunk struct {
	ChunkID  string    `json:"chunk_id"` // Unique identifier of the chunk
	Vector   []float32 `json:"vector"`   // Dense vector representation
	Text     string    `json:"text"`
	BlobURI  string    `json:"blob_uri"`
	MimeType string    `json:"mime_type"`
}

type EmbedRequestedPayload struct {
	DocumentID   string    `json:"document_id"`
	ChunkID      string    `json:"chunk_id"`
	Text         string    `json:"text"`
	BlobURI      string    `json:"blob_uri"`
	MimeType     string    `json:"mime_type"`
	OriginalType EventType `json:"original_type"`
}

// EmbedCompletedPayload is generated by the Embedder Worker after successful vectorization.
// It always returns an array of chunks (1-to-N relationship for large documents).
type EmbedCompletedPayload struct {
	DocumentID   string    `json:"document_id,omitempty"`  // Present only in Ingest flow
	Chunks       []Chunk   `json:"chunks"`                 // Array of vectorized fragments
	OriginalType EventType `json:"original_type"`          // Specifies if this was an Ingest or Search flow
	SearchTopK   int       `json:"search_top_k,omitempty"` // Passed through from SearchPayload for the Engine
}

// SearchCompletedPayload is the final result generated by the Search Engine.
type SearchCompletedPayload struct {
	Results []SearchResult `json:"results"` // Array of relevant hits
}

// SearchResult represents a single relevant match from the VectorDB.
type SearchResult struct {
	DocumentID string  `json:"document_id"` // Parent document ID
	ChunkID    string  `json:"chunk_id"`    // Specific fragment that matched
	Score      float32 `json:"score"`       // Cosine similarity score (closer to 1.0 is better)
	Text       string  `json:"text"`
	BlobURI    string  `json:"blob_uri"`
	MimeType   string  `json:"mime_type"`
}
