package events

// ClaimCheckPayload is a "receipt" (Claim Check) for a heavy file (Ingest flow)
type ClaimCheckPayload struct {
	DocumentID string            `json:"document_id"`
	BlobURI    string            `json:"blob_uri"`
	MimeType   string            `json:"mime_type"`
	SizeBytes  int64             `json:"size_bytes"`
	Metadata   map[string]string `json:"metadata,omitempty"`
}

// SearchPayload is generated by Gateway when a user makes a search request
type SearchPayload struct {
	QueryText string `json:"query_text,omitempty"`
	BlobURI   string `json:"blob_uri,omitempty"` // For Image-to-Image / Multimodal search
	TopK      int    `json:"top_k"`
}

// EmbedCompletedPayload is generated by Embedder Worker
type EmbedCompletedPayload struct {
	DocumentID   string    `json:"document_id,omitempty"` // Present only if it was an Ingest flow
	Vector       []float32 `json:"vector"`
	OriginalType EventType `json:"original_type"` // Indicates if this vector is for Ingest or Search
}

// SearchCompletedPayload is the final result generated by Engine
type SearchCompletedPayload struct {
	Results []SearchResult `json:"results"`
}

// SearchResult is a single hit from the VectorDB
type SearchResult struct {
	DocumentID string  `json:"document_id"`
	Score      float32 `json:"score"`
}
