global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'morphic_monad'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'host.docker.internal:8080'
          - 'gateway:8080'
